In [1]:
import pandas as pd
from numpy import *
#load dataset
data=pd.read_excel("Downloads/credit.xls")

#print(type(data))
#newdata=data.drop(['ID'],axis=1)
#print(newdata)
creditdata=data.values
print(creditdata)
print(type(creditdata))
x=creditdata[1:,1:24]#############Total 23 attributes  except id
y=creditdata[1:,24:] ######1   class

y=y.astype('int')
y=y.ravel()
#print(x.shape)
#print(y.shape)
#####split the data training and testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=5)
#print(x_train.shape)
#print(y_train.shape)
#print(x_test.shape)
#print(y_test.shape)

#create model Logistic Regression
def logreg():
    global acc_lg
    global L
    from sklearn.linear_model import LogisticRegression
    L=LogisticRegression(solver='liblinear')
    #############Train the model by training data set
    L.fit(x_train,y_train)
    ########Test the model
    y_pred_lg=L.predict(x_test)
    #########Find accuracy 
    from sklearn.metrics import accuracy_score
    acc_lg=accuracy_score(y_pred_lg,y_test)
    acc_lg=round(acc_lg*100,2)
    m.showinfo(title='Defaulter',message='Accuracy is'+str(acc_lg)+"%")
###############################################
###########Apply  KNN model  ##################
def knn():
    global acc_knn
    from sklearn.neighbors import KNeighborsClassifier
    KNN=KNeighborsClassifier(n_neighbors=5)
    KNN.fit(x_train,y_train)
    y_pred_knn=KNN.predict(x_test)
    from sklearn.metrics import accuracy_score
    acc_knn=accuracy_score(y_pred_knn,y_test)
    acc_knn=round(acc_knn*100,2)
    m.showinfo(title='Defaulter',message='Accuracy is'+str(acc_knn)+"%")
    

####################################################
#########   APPLY   NAIVE   BAYES   ALGORITHM ######
def naive():
    global acc_naive
    from sklearn.naive_bayes import GaussianNB
    N=GaussianNB()
    N.fit(x_train,y_train)
    y_pred_naive=N.predict(x_test)
    from sklearn.metrics import accuracy_score
    acc_naive=accuracy_score(y_pred_naive,y_test)
    acc_naive=round(acc_naive*100,2)
    m.showinfo(title='Defaulter',message='Accuracy is'+str(acc_naive)+"%")
    
####################################################
####APPLY  decisiontreeClassifier ##################
####################################################
def dtree():
    global acc_dt
    
    from sklearn.tree import DecisionTreeClassifier
    D=DecisionTreeClassifier()
    D.fit(x_train,y_train)
    y_pred_dt=D.predict(x_test)

    from sklearn.metrics import accuracy_score
    acc_dt=accuracy_score(y_pred_dt,y_test)
    acc_dt=round(acc_dt*100,2)
    m.showinfo(title='Defaulter',message='Accuracy is'+str(acc_dt)+"%")
    

def compare():
    global acc_knn;global acc_lg;global acc_naive
    global acc_dt
    import matplotlib.pyplot as plt
    clf=['knn','logistic','naivebayes','decisiontree']
    comp_acc=[acc_knn,acc_lg,acc_naive,acc_dt]
    plt.bar(clf,comp_acc,color=['yellow','red','blue','green'])
    plt.xlabel("Model comparison")
    plt.ylabel("Accuracy")
    plt.title("KNN vs Logistic vs naivebayes vs decisiontree")
    plt.show()
def predict():
    x1=float(v1.get())
    x2=float(v2.get())
    x3=float(v3.get())
    x4=float(v4.get())
    x5=float(v5.get())
    x6=float(v6.get())
    x7=float(v7.get())
    x8=float(v8.get())
    x9=float(v9.get())
    x10=float(v10.get())
    x11=float(v11.get())
    x12=float(v12.get())
    x13=float(v13.get())
    x14=float(v14.get())
    x15=float(v15.get())
    x16=float(v16.get())
    x17=float(v17.get())
    x18=float(v18.get())
    x19=float(v19.get())
    x20=float(v20.get())
    x21=float(v21.get())
    x22=float(v22.get())
    x23=float(v23.get())
    result=L.predict([[x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22,x23]])
    if result==0:
        L24.configure(text="NOT A DEFAULTER")
    else:
        L24.configure(text="DEFAULTER")
        
    
def reset():
    v1.set("")
    v2.set("")
    v3.set("")
    v4.set("")
    v5.set("")
    v6.set("")
    v7.set("")
    v8.set("")
    v9.set("")
    v10.set("")
    v11.set("")
    v12.set("")
    v13.set("")
    v14.set("")
    v15.set("")
    v16.set("")
    v17.set("")
    v18.set("")
    v19.set("")
    v20.set("")
    v21.set("")
    v22.set("")
    v23.set("")
    L24.configure(text="Fill up the details... ",bg='red')
########################################################
##############    GUI #######################
from tkinter import *
import tkinter.messagebox as m
w=Tk()
w.title("Credit Card Defaulter Prediction")
v1=StringVar()
v2=StringVar()
v3=StringVar()
v4=StringVar()
v5=StringVar()
v6=StringVar()
v7=StringVar()
v8=StringVar()
v9=StringVar()
v10=StringVar()
v11=StringVar()
v12=StringVar()
v13=StringVar()
v14=StringVar()
v15=StringVar()
v16=StringVar()
v17=StringVar()
v18=StringVar()
v19=StringVar()
v20=StringVar()
v21=StringVar()
v22=StringVar()
v23=StringVar()
L=Label(w,relief="groove",font=('arial',25,'bold'),text="CREDIT CARD DEFAULTER PREDICTION USING MACHINE LEARNING ",bg='cyan',fg='red')
B1=Button(w,bg="blue",fg='white',command=logreg,relief="solid",text='Logistic Regression',font=('arial',20,'bold'))
B2=Button(w,bg="blue",fg='white',command=knn,relief="solid",text='KNearest Neighbors',font=('arial',20,'bold'))
B3=Button(w,bg="blue",fg='white',command=naive,relief="solid",text='Naive Bayes',font=('arial',20,'bold'))
B4=Button(w,bg="blue",fg='white',command=dtree,relief="solid",text='Decision Tree Classifier',font=('arial',20,'bold'))
L.grid(row=1,column=1,columnspan=4)
B1.grid(row=2,column=1)
B2.grid(row=2,column=2)
B3.grid(row=2,column=3)
B4.grid(row=2,column=4)
####################################################
L1=Label(w,text='BALANCE',font=('arial',20,'bold'))
L2=Label(w,text='SEX',font=('arial',20,'bold'))
L3=Label(w,text='EDUCATION',font=('arial',20,'bold'))
L4=Label(w,text='MARRIAGE',font=('arial',20,'bold'))
L5=Label(w,text='AGE',font=('arial',20,'bold'))
L6=Label(w,text='PAY-1',font=('arial',20,'bold'))
L7=Label(w,text='PAY-2',font=('arial',20,'bold'))
L8=Label(w,text='PAY-3',font=('arial',20,'bold'))
L9=Label(w,text='PAY-4',font=('arial',20,'bold'))
L10=Label(w,text='PAY-5',font=('arial',20,'bold'))
L11=Label(w,text='PAY-6',font=('arial',20,'bold'))
L12=Label(w,text='BILL_AMT1',font=('arial',20,'bold'))
L13=Label(w,text='BILL_AMT2',font=('arial',20,'bold'))
L14=Label(w,text='BILL_AMT3',font=('arial',20,'bold'))
L15=Label(w,text='BILL_AMT4',font=('arial',20,'bold'))
L16=Label(w,text='BILL_AMT5',font=('arial',20,'bold'))
L17=Label(w,text='BILL_AMT6',font=('arial',20,'bold'))
L18=Label(w,text='PAY_AMT1',font=('arial',20,'bold'))
L19=Label(w,text='PAY_AMT2',font=('arial',20,'bold'))
L20=Label(w,text='PAY_AMT3',font=('arial',20,'bold'))
L21=Label(w,text='PAY_AMT4',font=('arial',20,'bold'))
L22=Label(w,text='PAY_AMT5',font=('arial',20,'bold'))
L23=Label(w,text='PAY_AMT6',font=('arial',20,'bold'))

E1=Entry(w,textvariable=v1,bg='yellow',font=('arial',20,'bold'))
E2=Entry(w,textvariable=v2,bg='yellow',font=('arial',20,'bold'))
E3=Entry(w,textvariable=v3,bg='yellow',font=('arial',20,'bold'))
E4=Entry(w,textvariable=v4,bg='yellow',font=('arial',20,'bold'))
E5=Entry(w,textvariable=v5,bg='yellow',font=('arial',20,'bold'))
E6=Entry(w,textvariable=v6,bg='yellow',font=('arial',20,'bold'))
E7=Entry(w,textvariable=v7,bg='yellow',font=('arial',20,'bold'))
E8=Entry(w,textvariable=v8,bg='yellow',font=('arial',20,'bold'))
E9=Entry(w,textvariable=v9,bg='yellow',font=('arial',20,'bold'))
E10=Entry(w,textvariable=v10,bg='yellow',font=('arial',20,'bold'))
E11=Entry(w,textvariable=v11,bg='yellow',font=('arial',20,'bold'))
E12=Entry(w,textvariable=v12,bg='yellow',font=('arial',20,'bold'))
E13=Entry(w,textvariable=v13,bg='yellow',font=('arial',20,'bold'))
E14=Entry(w,textvariable=v14,bg='yellow',font=('arial',20,'bold'))
E15=Entry(w,textvariable=v15,bg='yellow',font=('arial',20,'bold'))
E16=Entry(w,textvariable=v16,bg='yellow',font=('arial',20,'bold'))
E17=Entry(w,textvariable=v17,bg='yellow',font=('arial',20,'bold'))
E18=Entry(w,textvariable=v18,bg='yellow',font=('arial',20,'bold'))
E19=Entry(w,textvariable=v19,bg='yellow',font=('arial',20,'bold'))
E20=Entry(w,textvariable=v20,bg='yellow',font=('arial',20,'bold'))
E21=Entry(w,textvariable=v21,bg='yellow',font=('arial',20,'bold'))
E22=Entry(w,textvariable=v22,bg='yellow',font=('arial',20,'bold'))
E23=Entry(w,textvariable=v23,bg='yellow',font=('arial',20,'bold'))



L1.grid(row=3,column=1)
E1.grid(row=3,column=2)
L2.grid(row=3,column=3)
E2.grid(row=3,column=4)
L3.grid(row=4,column=1)
E3.grid(row=4,column=2)
L4.grid(row=4,column=3)
E4.grid(row=4,column=4)
#######################################
L5.grid(row=5,column=1)
E5.grid(row=5,column=2)
L6.grid(row=5,column=3)
E6.grid(row=5,column=4)
L7.grid(row=6,column=1)
E7.grid(row=6,column=2)
L8.grid(row=6,column=3)
E8.grid(row=6,column=4)
###################################################
L9.grid(row=7,column=1)
E9.grid(row=7,column=2)
L10.grid(row=7,column=3)
E10.grid(row=7,column=4)
L11.grid(row=8,column=1)
E11.grid(row=8,column=2)
L12.grid(row=8,column=3)
E12.grid(row=8,column=4)
########################################
L13.grid(row=9,column=1)
E13.grid(row=9,column=2)
L14.grid(row=9,column=3)
E14.grid(row=9,column=4)
L15.grid(row=10,column=1)
E15.grid(row=10,column=2)
L16.grid(row=10,column=3)
E16.grid(row=10,column=4)
################
L17.grid(row=11,column=1)
E17.grid(row=11,column=2)
L18.grid(row=11,column=3)
E18.grid(row=11,column=4)
L19.grid(row=12,column=1)
E19.grid(row=12,column=2)
L20.grid(row=12,column=3)
E20.grid(row=12,column=4)
##############################
L21.grid(row=13,column=1)
E21.grid(row=13,column=2)
L22.grid(row=13,column=3)
E22.grid(row=13,column=4)
L23.grid(row=14,column=1)
E23.grid(row=14,column=2)

##########################
B5=Button(w,relief="solid",bg='blue',fg="white",text="SUBMIT",font=('arial',20,'bold'),command=predict)
B6=Button(w,relief="solid",bg='blue',fg='white',text="RESET",font=('arial',20,'bold'),command=reset)
B7=Button(w,relief="solid",bg='blue',fg='white',text="COMPARE",font=('arial',20,'bold'),command=compare)
B7.grid(row=15,column=1)
B5.grid(row=15,column=2)
B6.grid(row=15,column=3)
L24=Label(w,text='Fill up the details...',height=2,width=20,bg='white',relief='solid',font=('arial',20,'bold'))
L24.grid(row=14,column=4,rowspan=2)
##############################################
Lend=Label(w,relief="solid",font=('arial',25,'bold'),text="CREDIT CARD DEFAULTER PREDICTION USING MACHINE LEARNING",bg='cyan',fg='red',)
Lend.grid(row=16,column=1,columnspan=4)
w.mainloop()



[['ID' 'LIMIT_BAL' 'SEX' ... 'PAY_AMT5' 'PAY_AMT6'
  'default payment next month']
 [1 20000 2 ... 0 0 1]
 [2 120000 2 ... 0 2000 1]
 ...
 [29998 30000 1 ... 2000 3100 1]
 [29999 80000 1 ... 52964 1804 1]
 [30000 50000 1 ... 1000 1000 1]]
<class 'numpy.ndarray'>
